### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by flip111** [graphaware/neo4j-uuid#11]
not sure if i'm doing anything wrong here. Infos:

Neo4j version: neo4j-community_windows-x64_2_2_6.exe

```
D:\dev\neo4j\plugins>dir
 Volume in drive D is Data
 Volume Serial Number is 2E83-BAB4

 Directory of D:\dev\neo4j\plugins

18-10-2015  23:58    <DIR>          .
18-10-2015  23:58    <DIR>          ..
18-10-2015  23:55        13.191.699 graphaware-server-community-all-2.2.6.35.jar
18-10-2015  23:54            13.870 graphaware-uuid-2.2.6.35.7.jar
13-10-2015  22:47               279 README.txt
               3 File(s)     13.205.848 bytes
               2 Dir(s)  18.840.903.680 bytes free
```

md5
```
2990da3ce90f56cf0c6e340e9b3ca7f0 *graphaware-server-community-all-2.2.6.35.jar
4b3ad2559e9304fcb1e0bcaec312fdc1 *graphaware-uuid-2.2.6.35.7.jar
```

![image](https://cloud.githubusercontent.com/assets/2244480/10567016/3c2a7c96-75f7-11e5-83d6-418a446186a8.png)

`D:\dev\neo4j\data\neo4j.properties`:
```
com.graphaware.runtime.enabled=true
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
```
(the rest of the config is commented out with `#` or whitelines)

Queries (on empty database)
```
CREATE (n {bar: "foo"}) RETURN n
MATCH n RETURN n
```

![image](https://cloud.githubusercontent.com/assets/2244480/10567031/9ebaa5d4-75f7-11e5-8efd-83aace71b907.png)

Tried restarting the server a couple of times and tried a few queries as well. By the way i was very confused by `Note that "UIDM" becomes the module ID.`. So i tried replacing `UIDM` with several combinations of version numbers at first ... not sure if that messed something up.

In messages.log i find this
```
2015-10-18 22:12:31.468+0000 INFO  [o.n.k.i.DiagnosticsManager]: org.neo4j.server.db.tuning.properties=C:\Users\          \AppData\Roaming\Neo4j Community\neo4j.properties
2015-10-18 22:12:31.468+0000 INFO  [o.n.k.i.DiagnosticsManager]: org.neo4j.server.database.location=D:\dev\neo4j\data
```

Which is strange because the graphical interface says `neo4j.properties` is located elsewhere o_O

But in the same log i find:
```
2015-10-18 22:12:31.468+0000 INFO  [o.n.k.i.DiagnosticsManager]: com.graphaware.runtime.enabled=true
2015-10-18 22:12:31.468+0000 INFO  [o.n.k.i.DiagnosticsManager]: remote_shell_enabled=true
2015-10-18 22:12:31.468+0000 INFO  [o.n.k.i.DiagnosticsManager]: com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
```

Which makes me think it DID pick up on the configuration settings i've added ...

**Comment by ikwattro** [comment]
Hi,

Is neo4j installed with the installer or downloaded and extracted ?

**Comment by flip111** [comment]
Just used the installer exe. How can i locate `console.log`?

**Comment by ikwattro** [comment]
Hi,

I think it is in the ApplicationPath directory.

However the graphaware-framework don't work on Windows when neo4j is installed with the `installer.exe`, only when extracted from the zip.

https://github.com/graphaware/neo4j-framework#getting-graphaware-framework

**Comment by flip111** [comment]
I returned today to do some queries and to my surprise the uuid are showing ... i didn't change anything! You might want to revisit that requirement that you can not use the installer exe ...
