### ISSUE TITLE
Support for neo4j 2.3

### ISSUE THREAD

**Issue by oren** [graphaware/neo4j-uuid#12]
I noticed there is a 2.3 branch. is it planned to be merged soon?
Thanks!

**Comment by MicTech** [comment]
Yes, it will. Please give us few more days. Thank you.

**Comment by ikwattro** [comment]
Hi @oren , The modules have been upgraded to 2.3 and are available for download on our products page : 

http://graphaware.com/products/

Please test and report.

Thanks !

**Comment by oren** [comment]
@ikwattro will do. thank you!
