### ISSUE TITLE
Bytes taken by UUID

### ISSUE THREAD

**Issue by digitalresonance** [graphaware/neo4j-uuid#15]
Hi,

This is not really an issue, more of a query, didn't know where else to ask.

How does this extension store the values internally within the database?
Does it store them as UUID ? i.e 128 bits (16bytes) 
or is it stored as a string ? i.e (32 bytes)

Thanks.

**Comment by bachmanm** [comment]
Currently the UUID is stored as a String, but it would be trivial to change that. It's for index friendliness, primarily. To be honest, I'm not entirely sure how Lucene would handle raw bytes.

**Comment by digitalresonance** [comment]
Thanks for replying Michael.

I believe Lucene does support indexing using byte arrays. I am not altogether sure if it would serve this purpose but if it works it would help shave a bit of overhead on larger datasets.

**Comment by bachmanm** [comment]
Closing - created https://github.com/graphaware/neo4j-uuid/issues/16
