### ISSUE TITLE
Investigate faster UUID option

### ISSUE THREAD

**Issue by bachmanm** [graphaware/neo4j-uuid#16]
read this http://blog.mikemccandless.com/2014/05/choosing-fast-unique-identifier-uuid.html and investigate, whether we can do better that we're doing now

**Comment by digitalresonance** [comment]
The above link is a good find. I think by using UUID V1, the time stamp and mac address should provide a pattern that is easily looked up on an index. If we could also store it as a byte array, it might reduce memory overhead a little.
