### ISSUE TITLE
Feature request: Ability to choose to generate v4 UUIDs 

### ISSUE THREAD

**Issue by Joshfindit** [graphaware/neo4j-uuid#21]
As UUID v1 uses the MAC address of the local machine, it keeps information that's not necessary in all situations.

v4 is random, so requires no system calls to generate.
`java.util.UUID.randomUUID();`
Found this as well: http://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#randomUUID--

**Comment by Joshfindit** [comment]
Related to https://github.com/graphaware/neo4j-uuid/issues/19

**Comment by ikwattro** [comment]
Fixed by #31
