### ISSUE TITLE
UUID is not generate

### ISSUE THREAD

**Issue by IsraelEndale** [graphaware/neo4j-uuid#22]
Steps i follwed 
Installed neo4j-community_macos_3_0_3.dmg
Dropped both graphaware-server-community-all-3.0.3.39.jar and graphaware-uuid-3.0.3.39.10.jar at data/plugins

added the following at ~/Neo4j/.neo4j.conf

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is uuid:
com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is no relationships:
#com.graphaware.module.UIDM.relationship=isType('Type1')

#optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#optional, default is uuidRelIndex
com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex

My entity has the following info:

@GraphId
    private Long id;

    private String uuid;

But no uuid is generated for the Entity, what did i missed?

Cheers!
[debug.pdf](https://github.com/graphaware/neo4j-uuid/files/367087/debug.pdf)

**Comment by agdelen** [comment]
Hi there, can you tell more about this compatibility issue? Is it going to be fixed anytime soon? 

Thanks

**Comment by ikwattro** [comment]
We plan to fix it at some point if possible. 

Now to be honest it is not in the top list of our priorities of research and development mainly because production usages don't use installers, neither do we.

**Comment by osuushi** [comment]
That sounds reasonable, but you guys might want to mention this in the plugin readme (although I do see it's in the framework readme).

**Comment by polyakoff** [comment]
>you guys might want to mention this in the plugin readme
+1
