### ISSUE TITLE
No GraphAware Runtime is registered with the given database

### ISSUE THREAD

**Issue by albert-the-creator** [graphaware/neo4j-uuid#26]
I have a fresh Neo4j 3.0.4 install using the 3.0.4.43 framwork plugins.

Timetree is installed and working flawlessly, however, I cannot get uuid to work.
`CALL ga.uuid.findNode("uuid") YIELD  node as n` always throws the error `Failed to invoke procedure ga.uuid.findNode: Caused by: java.lang.IllegalStateException: No GraphAware Runtime is registered with the given database`

I've attached the neo4j.conf file.
[neo4j.conf.txt](https://github.com/graphaware/neo4j-uuid/files/407910/neo4j.conf.txt)

<img width="549" alt="screen shot 2016-08-08 at 6 49 59 pm" src="https://cloud.githubusercontent.com/assets/20915233/17499330/c3189658-5d9a-11e6-80eb-cbd5154f2252.png">

Any idea on what i'm doing wrong?

**Comment by bachmanm** [comment]
It seems like the last release didn't go well - give us a couple of hours

**Comment by bachmanm** [comment]
OK, could you please download the same framework file again and replace the old one? It's been fixed. http://products.graphaware.com/download/framework-server-community/latest

Leave everything else as is.

**Comment by albert-the-creator** [comment]
Great, it works! Thank you.
