### ISSUE TITLE
UUID is not available via cypher immediately upon creation

### ISSUE THREAD

**Issue by voidstardb** [graphaware/neo4j-uuid#3]
With graphaware framework and neo4j-uuid plugins installed:

1. Open the neo4j browser (http://localhost:7474/browser)
1. Enter the following cypher: `create (n {name: "foo"}) return n, n.uuid;`
1. Enter the following cypher: `match (n {name: "foo"}) return n, n.uuid;`

Actual result:
`{name: "foo"}, null` (from create)
`{name: "foo", uuid: "<UUID>"}, <UUID>` (from match)

Expected result:
`{name: "foo", uuid: "<UUID>"}, <UUID>`
`{name: "foo", uuid: "<UUID>"}, <UUID>`

This issue is reproducible via neo's REST API as well. Not returning the UUID at time of create requires additional cypher queries to get the UUID.

**Comment by bachmanm** [comment]
Unfortunately, this is how Neo4j works today - if you create a node a return it immediately, its contents do not reflect changes performed by transaction event handlers (i.e., it does not re-read the node before returning it). This is true for all the APIs, the browser, etc. A separate call must be made to get the UUID and I don't think there's any way we can change this behaviour in the framework.

**Comment by voidstardb** [comment]
Thanks for the explanation.

**Comment by voidstardb** [comment]
Just for future reference: http://neo4j.com/docs/2.2.1/javadocs/org/neo4j/graphdb/event/TransactionEventHandler.html

> beforeCommit
> The transaction is still open when this method is invoked, making it possible to perform mutating operations in this method. This is however highly discouraged. Changes made in this method are not guaranteed to be visible by this or other TransactionEventHandlers.

There's no other obvious lifecycle hook in which to place the UUID functionality. So, I guess we're stuck with this for now.

**Comment by Bretto** [comment]
What a shame...

**Comment by Crodaycat** [comment]
Is there something new about this?

**Comment by venkat125** [comment]
But, it is _NICE TO HAVE_ feature though.
Can i get the below doubt cleared please?

- Do the UUID plugin from Graphaware will be unique even if we've more Neo4j (instance in the hosting/ running ip's in cloud)? @bachmanm
