### ISSUE TITLE
uuid not creating for relationship

### ISSUE THREAD

**Issue by amareshwarbhat** [graphaware/neo4j-uuid#30]
Hello,

I am able to get the UUIDs for all the nodes, but not for the relationships. Please find the details below:

**Product Versions**
I am using Neo4j  version 3.0.6
I have added 2 jars
1: graphaware-server-community-all-3.0.6.43.jar
2: graphaware-uuid-3.0.6.43.11.jar

**neo4j.config file entries for UUID**
com.graphaware.runtime.enabled=true
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
com.graphaware.module.UIDM.uuidProperty=uuid
com.graphaware.module.UIDM.stripHyphens=false
com.graphaware.module.UIDM.uuidIndex=uuidIndex
com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex
com.graphaware.module.UIDM.relationship=com.graphaware.common.policy.all.IncludeAllRelationships

I observed the neo4j.log file entries during startup as well as during the creation of a new relationship, but there were no errors observed. 

Please let me know if any of my config entries are wrong. Appreciate your help.

**Comment by bachmanm** [comment]
Strange, this should work.Ccould you try with `com.graphaware.module.UIDM.relationship=all`?

**Comment by amareshwarbhat** [comment]
Thanks bachmanm.
That works fine. Cool

**Comment by bachmanm** [comment]
Which raises the question why your original config did not work. I'll leave the issue open until some GraphAware hero has a quick look. Thanks!

**Comment by ikwattro** [comment]
Just tried 3.0.6 with same configuration, works fine for me. Closing

**Comment by espiegelberg** [comment]
While doing some work on a small PR, I was also able to reproduce that the same configuration works fine for me. @ikwattro is right, this can be closed.

**Comment by ikwattro** [comment]
Thx @espiegelberg

**Comment by Rim-k** [comment]
Hello, 

This post is quite old but I have the same issue as @amareshwarbhat :
No uuid generated for the relationships while using : **com.graphaware.module.UIDM.relationship=com.graphaware.common.policy.all.IncludeAllRelationships**

But I do have a uuid on the relationships using: 
**com.graphaware.module.UIDM.relationship=all**

**My complete conf:** 
com.graphaware.runtime.enabled=true
#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
#optional, default is uuid:
#com.graphaware.module.UIDM.uuidProperty=uuid
#optional, default is false:
#com.graphaware.module.UIDM.stripHyphens=false
#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')
#optional, default is no relationships:
com.graphaware.module.UIDM.relationship=all
#optional, default is uuidIndex
#com.graphaware.module.UIDM.uuidIndex=uuidIndex
#optional, default is uuidRelIndex
#com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex

I'm using **neo4j:3.5.5-enterprise** docker image

Thx
