### ISSUE TITLE
Relationship index

### ISSUE THREAD

**Issue by tavolate** [graphaware/neo4j-uuid#33]
What do you mean with relationship index?

com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex

I read that it is not possible to index a relationship property in neo4j

**Comment by bachmanm** [comment]
It is possible in the "legacy" index, which this module is using.

**Comment by tavolate** [comment]
ok, thank you. When I create a node the assigned uuid it is not just returned. I have to make a new call.

CREATE (a:Node) RETURN a

The returned a is without uuid

MATCH (a:Node) RETURN a

The returned a has the uuid

Is it normal?

**Comment by bachmanm** [comment]
yes, please see https://github.com/graphaware/neo4j-uuid/issues/3
