### ISSUE TITLE
UUID isn't setting for Neo4j Enterprise v3.1

### ISSUE THREAD

**Issue by scy0846** [graphaware/neo4j-uuid#35]
I installed the plugin by placing the two .jar files in the plugins folder and then putting the below text in the neo4j.conf file.

`com.graphaware.runtime.enabled=true`

`#UIDM becomes the module ID:`
`com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper`

`#optional, default is uuid:`
`com.graphaware.module.UIDM.uuidProperty=uuid`

`#optional, default is false:`
`com.graphaware.module.UIDM.stripHyphens=false`

`#optional, default is all nodes:`
`com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')`

`#optional, default is no relationships:`
`com.graphaware.module.UIDM.relationship=isType('Type1')`

`#optional, default is uuidIndex`
`com.graphaware.module.UIDM.uuidIndex=uuidIndex`

`#optional, default is uuidRelIndex`
`com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex`

Currently, my database looks like normal except under "Property Keys" it's showing "_GA_TX_MODULE_UIDM" which confuses me because I believe the property should be "uuid".

When clicking on the property key  "_GA_TX_MODULE_UIDM" it gives me nothing in the query window. I don't believe I have done anything wrong with it. I've restarted, I started and stopped the server numerous times. Is it because it's v 3.1?

**Comment by scy0846** [comment]
Apparently adding the optional pieces that make it Label1 or Label2 was my issue. Not sure why I missed that. Deleted those lines and now it works

**Comment by venkat125** [comment]
> 
> 
> Apparently adding the optional pieces that make it Label1 or Label2 was my issue. Not sure why I missed that. Deleted those lines and now it works

That's right. You saved my day @CaffeinatedFunctionality  Thanks
