### ISSUE TITLE
UUID and TimeTree aren't playing well together

### ISSUE THREAD

**Issue by jeremykendall** [graphaware/neo4j-uuid#4]
I added UUID to a project and then, after confirming that UUID worked, added TimeTree. Once I enabled TimeTree, UUID no longer added a `uuid` property to newly created nodes.  If I then remove TimeTree and restart, UUID will add a `uuid` property to all nodes during startup and will again add a `uuid` to each new node.

### Environment

* Neo4j Enterprise 2.2.1 - standalone server
* GraphAware jars (downloaded from http://graphaware.com/products/):
    * graphaware-server-enterprise-all-2.2.1.30.jar
    * graphaware-timetree-2.2.1.30.21.jar
    * graphaware-uuid-2.2.1.30.7.jar
* Mac OSX 10.10.3

Java
```
$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

$ javac -version
javac 1.8.0_05
```

Configuration (`neo4j-server.properties`):
```
# GraphAware
com.graphaware.runtime.enabled=true

#
# GraphAware TimeTree
#
# A Runtime module that takes care of attaching the events like this (TT is the ID of the module)
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

# Nodes which represent events and should be attached automatically have to be defined
com.graphaware.module.TT.event=hasLabel('Event')

# Optionally, a property on the event nodes that represents the the time (long) at which the event took place must be specified (defaults to "timestamp")
# com.graphaware.module.TT.timestamp=time

# Optionally, a resolution can be specified (defaults to DAY)
com.graphaware.module.TT.resolution=SECOND

# Optionally, a time zone can be specified (defaults to UTC)
# com.graphaware.module.TT.timezone=GMT+1

# Optionally, a relationship type with which the events will be attached to the tree can be specified (defaults to AT_TIME)
# com.graphaware.module.TT.relationship=SENT_ON

# autoAttach must be set to true
com.graphaware.module.TT.autoAttach=true

#
# GraphAware UUID
#
#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
```

Please let me know what additional information will be necessary or helpful.

**Comment by bachmanm** [comment]
Hi Jeremy,

Please try

com.graphaware.module.TT.2=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

Instead of

com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

Modules have to have a unique order.

**Comment by jeremykendall** [comment]
Aha! That makes perfect sense. I'll give it a shot and let you know.

**Comment by jeremykendall** [comment]
That did it. Thanks!
