### ISSUE TITLE
if i remove this uuid plugin, will uuid still persists?

### ISSUE THREAD

**Issue by vvavepacket** [graphaware/neo4j-uuid#43]
if i remove the uuid plugin, will the uuid property on the nodes still exists?

**Comment by bachmanm** [comment]
Yes, it will, but no new UUIDs will be assigned, nor will the existing UUIDs be prevented from modification or deletion. Why do you want to remove the plugin?

**Comment by vvavepacket** [comment]
I dont want to remove plugin.. Just curious.. Thanks for answering. Closing as resolved.
