### ISSUE TITLE
Conflict with apoc.refactor.mergeNodes

### ISSUE THREAD

**Issue by SimonThordal** [graphaware/neo4j-uuid#45]
APOC mergeNodes function takes an array of nodes and merges their properties, starting from the last position in the array and merging each member onto the preceding member. When you use neo4j-uuid this fails with:

![image](https://user-images.githubusercontent.com/1394424/34357175-140f749a-ea45-11e7-97b8-824e145e1aed.png)

I don't get any log output that I can see, but I am assuming this is because they are trying to copy over the uuid property when merging the nodes.

**Comment by bachmanm** [comment]
Correct, the UUID module prevents anyone from messing with the UUID (i.e., changing or deleting) that's already been assigned to the node.

We would definitely accept a PR where this functionality is disabled by setting something like
`com.graphaware.module.UIDM.unsafe=true`

**Comment by SimonThordal** [comment]
Thanks @bachmanm. My java-fu is pretty weak, but I'll spread the word in the APOC slack channel and maybe someone from there will be able to take a look at it. So far I worked around it by switching from the UIDM module to an apoc.trigger that adds a uuid on node creation.

**Comment by bachmanm** [comment]
fixed in 3.3.3.52.16
