### ISSUE TITLE
Feature request : ga.uuid.findNode() returning null

### ISSUE THREAD

**Issue by ophileon** [graphaware/neo4j-uuid#46]
### in short
`ga.uuid.findNode()`  now returns an error if the uuid is not found in the index. Would be great to have it return `null` instead.

### my usecase
I have a number of nodemaps (an export of a source db) and I need to update the target db. The target db does not necessarily contain all the nodes, so it's an update or create. 
Since we do not know anything about the labels of the nodes that are export, we cannot rely on Neo4j labels.

```
WITH [
              {labels:['X','Y','Z'],properties:{uuid:'uuid1',propa:'x'}},
              {labels:['A','B','C'],properties:{uuid:'uuid2',propb:'abc'}}
] AS nodemaps

UNWIND nodemaps AS nodemap
RETURN nodemap.properties.uuid, ga.uuid.findNode(nodemap.properties.uuid) IS NULL AS nodeExists
```
would then be possible.

**Comment by bachmanm** [comment]
Fixed in 3.3.2.51.15

**Comment by ikwattro** [comment]
even better:)

**Comment by ophileon** [comment]
cool :)  thx guys.
