### ISSUE TITLE
uuid indexes

### ISSUE THREAD

**Issue by stevecreedon** [graphaware/neo4j-uuid#48]
I'm trying to run the graphaware annotate function on Neo4j Enterprise 3.3.0 using the stanford tokenizer pipeline and it's very slow. I've included the uuid plugin and that does seem to add the uuid property to every node. But when I call db.indexes I only see the recommended indexes I created explicitly:

"INDEX ON :Tag(value)"
"INDEX ON :AnnotatedText(id)"
"INDEX ON :Sentence(id)"
"INDEX ON :Tag(id)"

It feels to me I should also see indexes for all the types of node being created but I see nothing and I suspect that's why it's so very slow. My configuration is:

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is uuid:
com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is false:
com.graphaware.module.UIDM.stripHyphens=false

#optional, default is all nodes:
#com.graphaware.module.UIDM.node=hasLabel('Label1') || hasLabel('Label2')

#optional, default is no relationships:
#com.graphaware.module.UIDM.relationship=isType('Type1')

#optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#optional, default is uuidRelIndex
#com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex

Am I doing something obviously wrong ?

**Comment by ikwattro** [comment]
@stevecreedon The uuid module use Lucene indexes, not schema ones, this is why you do not see it with the db.indexes call.

Also the UUID module will not improve performance of the NLP processing.

Can you open a new issue in neo4j-nlp with the text you are trying to annotate as well as the cypher query used for running the annotation. Thanks.
