### ISSUE TITLE
No UUID generated

### ISSUE THREAD

**Issue by Bretto** [graphaware/neo4j-uuid#5]
Neo4j 2.2.2
plugins
graphaware-server-community-all-2.2.2.31.jar
graphaware-uuid-2.2.2.31.7.jar

conf neo4j.properties
com.graphaware.runtime.enabled=true
#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

in the browser console
CREATE (n:Test {name:"World"}) RETURN n
results:
Test  <id>:0 name:World
 
No uuid...

**Comment by Bretto** [comment]
It's working now maybe a cache issue in the browser

**Comment by Bretto** [comment]
acctualy this is what happened : UUID is not available via cypher immediately upon creation

**Comment by bachmanm** [comment]
True, you have to "re-read" the node. This is not ideal, but unfortunately not something we can do anything about I'm afraid. Hope you can still use it!
