### ISSUE TITLE
Neo4j become read only after jvm heap error

### ISSUE THREAD

**Issue by sdhost** [graphaware/neo4j-uuid#52]
Hi,
    I'm using neo4j-uuid with neo4j-desktop on version 3.4.9. 
    I'm trying to create about 30M nodes using query parameters in python by dividing it into small batches containing 5000 nodes. The insertion is fast in the beginning and slowing down after 20 batches, the neo4j throwed a OutOfMemory exception and restarted. Then I've found that the neo4j database cannot executing any create operation and delete operations. When I disabled uuid plugin, the database recovered to normal condition. The read-only problem returned when I enabled the uuid plugin.

I wonder how can I recover the uuid in my database, Thanks!

**Comment by dmiranda2791** [comment]
hey I am facing this same issue on neo4j v3.5.9, graphaware uuid v3.5.4.53.17 and graphaware framework v3.5.4.53.jar. I just upgraded the db and I am not able to do any create, delete or update query. If I disable the plugin the everything goes well.

**Comment by luanne** [comment]
@sdhost is this one still an issue?
