### ISSUE TITLE
Prepend string to UUIDs on creation?

### ISSUE THREAD

**Issue by valerioleo** [graphaware/neo4j-uuid#61]
Hello everyone, thanks for the cool plugin! I have implemented it in our organisation and have some questions.

Before `neo4j-uuid`, we were generating our own id like `CREATE (Project {id: 'project_abc123....'})`. 
The `id` property we have always used is the concatenation of `project_` + `uuid` and we do the same for other nodes, e.g. `user_<uuid>`, `subscription_<uuid>` and so on...

Is there any way we can prepend a different string to uuid for each specific node? It would be awesome to be able config file similar to:
```
#optional, default is uuid:
com.graphaware.module.UIDM.uuidPrefix=[[Project, _project], [User, _user], ...etc]
```

Thank you so much for any help!

**Comment by ikwattro** [comment]
Hi @valerioleo . As of today we do not plan to add this feature ourself. We would of course welcome any contribution supplemented by sufficient unit tests.
