### ISSUE TITLE
Can't use the package with version 2.3.0-M02

### ISSUE THREAD

**Issue by levidamian** [graphaware/neo4j-uuid#8]
I did a migration from 2.2.5 to 2.3.0-M02 and I had to comment these lines in order to restart the server,
#com.graphaware.runtime.enabled=true
#com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
I cannot generare UUID at the moment of node creation.

**Comment by ikwattro** [comment]
This is the expected behavior, our releases are inlined with neo4j stable versions.

Once Neo4j2.3 stable will be released, our modules will be upgraded as such.
